Algoritmo "exercício15"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que define se o valor é positivo ou negativo(zero é considerado positivo)
// Autor(a)    : Rebeca Leite Pereira
// Data atual  : 19/09/2021
Var
// Seção de Declarações das variáveis 
valor:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(valor)
se(valor>-1)entao
escreva("POSITIVO")
senao
escreva("NEGATIVO")
fimse


Fimalgoritmo