Algoritmo "exercicio5"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   :  Algoritmo aprensenta valor antecessor do valor digitado
// Autor(a)    : Rebeca Leite Pereira
// Data atual  : 12/09/2021
Var
num:real
antecessor:real

Inicio
escreva("Digite um valor para saber seu antecessor: ")
leia(num)
antecessor <- num-1
escreva("Valor antecessor: ", antecessor)

Fimalgoritmo