Algoritmo "exercício33"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que lê dois números e determina se são valores iguais ou qual dos dois valores é maior.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/09/2021
var
x,y:real

Inicio
leia(x,y)

se(x = y) entao
escreva("São números iguais")

senao
se(x > y) entao
escreva("O primeiro é maior")

senao
escreva("O segundo é maior")

fimse
fimse

Fimalgoritmo