Algoritmo "exercício20"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que organiza dois valores em ordem crescente.
// Autor(a)    : Rebeca Leite Pereira
// Data atual  : 19/09/2021
Var
// Seção de Declarações das variáveis 
x,y:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(x,y)
se (x>y) entao
escreva(y,", ",x)
senao
escreva(x,", ",y)
fimse

Fimalgoritmo
