Algoritmo "exercício19"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson
// Descrição   : Algoritmo que define entre dois termos  o maior dentre eles.
// Autor(a)    : Rebeca Leite Pereira
// Data atual  : 19/09/2021
Var
// Seção de Declarações das variáveis 
x,y:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
leia(x,y)
se (x>y) entao
escreva(x," é maior que ",y)
senao
escreva(y," é maior que ",x)
fimse

Fimalgoritmo